#pragma once

#include <array>
#include <vector>

#include <juce_core/juce_core.h>

namespace liveflow
{
/**
 * @struct DuckBand
 * @brief Parameters for a single frequency-domain ducking notch filter.
 *
 * Each DuckBand drives one IIR bell/notch filter inside the SpectralDuckEQ.
 * The filter's center frequency and Q are fixed by the Profile; only the depth
 * is modulated in real-time by voicePresence (0 = flat, 1 = full notch).
 */
struct DuckBand
{
    float centerHz = 1000.0f;   ///< Notch center frequency (Hz)
    float bandwidthQ = 1.5f;    ///< Filter Q (bandwidth). Higher = narrower notch
    float depthDb = 6.0f;       ///< Maximum ducking depth when voice is fully present (dB)
    bool enabled = true;        ///< Whether this band is active

    bool operator== (const DuckBand& other) const noexcept
    {
        return juce::approximatelyEqual (centerHz, other.centerHz)
            && juce::approximatelyEqual (bandwidthQ, other.bandwidthQ)
            && juce::approximatelyEqual (depthDb, other.depthDb)
            && enabled == other.enabled;
    }
};

/**
 * @struct EnergyZone
 * @brief A complete parameter recipe for one energy level range.
 *
 * The Profile partitions the backing track's LUFS range into N zones.
 * Each zone stores its own optimal RuntimeSettings values and spectral
 * duck EQ configuration. During live performance, the engine interpolates
 * between adjacent zones based on the current backing LUFS.
 */
struct EnergyZone
{
    float lufsLower = -100.0f;  ///< LUFS lower bound of this zone (inclusive)
    float lufsUpper = 0.0f;     ///< LUFS upper bound of this zone (exclusive)

    // ── Macro parameters (map to RuntimeSettings) ──
    float balanceDb = 3.0f;
    float dynamicsPercent = 0.0f;
    float speedMs = 120.0f;
    float rangeDb = 8.0f;
    float anchorDb = -24.0f;
    float noiseGateDb = -45.0f;
    float duckFloorDb = 10.0f;
    float boostCeilingDb = 6.0f;
    float presenceReleaseMs = 80.0f;

    // ── Spectral duck EQ bands ──
    std::vector<DuckBand> duckBands;

    /** @brief Linearly interpolate all numeric fields between this zone and another. */
    [[nodiscard]] EnergyZone interpolateWith (const EnergyZone& other, float t) const noexcept
    {
        const auto lerp = [] (float a, float b, float factor) { return a + factor * (b - a); };

        EnergyZone result;
        result.lufsLower = lerp (lufsLower, other.lufsLower, t);
        result.lufsUpper = lerp (lufsUpper, other.lufsUpper, t);

        result.balanceDb = lerp (balanceDb, other.balanceDb, t);
        result.dynamicsPercent = lerp (dynamicsPercent, other.dynamicsPercent, t);
        result.speedMs = lerp (speedMs, other.speedMs, t);
        result.rangeDb = lerp (rangeDb, other.rangeDb, t);
        result.anchorDb = lerp (anchorDb, other.anchorDb, t);
        result.noiseGateDb = lerp (noiseGateDb, other.noiseGateDb, t);
        result.duckFloorDb = lerp (duckFloorDb, other.duckFloorDb, t);
        result.boostCeilingDb = lerp (boostCeilingDb, other.boostCeilingDb, t);
        result.presenceReleaseMs = lerp (presenceReleaseMs, other.presenceReleaseMs, t);

        // Interpolate duck bands (use the larger set as basis)
        const auto bandCount = juce::jmax (duckBands.size(), other.duckBands.size());
        result.duckBands.resize (bandCount);

        for (size_t i = 0; i < bandCount; ++i)
        {
            const auto& a = i < duckBands.size() ? duckBands[i] : DuckBand {};
            const auto& b = i < other.duckBands.size() ? other.duckBands[i] : DuckBand {};
            result.duckBands[i].centerHz = lerp (a.centerHz, b.centerHz, t);
            result.duckBands[i].bandwidthQ = lerp (a.bandwidthQ, b.bandwidthQ, t);
            result.duckBands[i].depthDb = lerp (a.depthDb, b.depthDb, t);
            result.duckBands[i].enabled = t < 0.5f ? a.enabled : b.enabled;
        }

        return result;
    }
};

/**
 * @class TrackProfile
 * @brief A complete acoustic fingerprint generated by the Smart Track Profiler.
 *
 * Contains N energy zones, each with its own optimal parameter set and spectral
 * duck EQ configuration. Supports JSON serialization (for cross-project export)
 * and binary serialization (for DAW state persistence).
 */
class TrackProfile
{
public:
    static constexpr int minZones = 2;
    static constexpr int maxZones = 8;
    static constexpr int defaultZones = 3;
    static constexpr int minBands = 1;
    static constexpr int maxBands = 8;
    static constexpr int defaultBands = 3;

    juce::String name;
    juce::Time created;
    double sampleRate = 44100.0;
    std::vector<EnergyZone> zones;

    // ────────────────────────────────────────────
    // Interpolation
    // ────────────────────────────────────────────

    /**
     * @brief Given a current backing LUFS, find the enclosing zones and interpolate.
     *
     * If LUFS falls below all zones, returns the first zone.
     * If LUFS falls above all zones, returns the last zone.
     * Otherwise, linearly interpolates between the two adjacent zones.
     */
    [[nodiscard]] EnergyZone interpolate (float currentBackingLufs) const
    {
        if (zones.empty())
            return {};

        if (zones.size() == 1 || currentBackingLufs <= zones.front().lufsLower)
            return zones.front();

        if (currentBackingLufs >= zones.back().lufsUpper)
            return zones.back();

        for (size_t i = 0; i + 1 < zones.size(); ++i)
        {
            if (currentBackingLufs >= zones[i].lufsLower && currentBackingLufs < zones[i + 1].lufsLower)
            {
                const auto range = zones[i + 1].lufsLower - zones[i].lufsLower;

                if (range < 0.01f)
                    return zones[i];

                const auto t = (currentBackingLufs - zones[i].lufsLower) / range;
                return zones[i].interpolateWith (zones[i + 1], t);
            }
        }

        return zones.back();
    }

    /**
     * @brief Returns the index of the zone that best matches the given LUFS, without interpolation.
     */
    [[nodiscard]] int findZoneIndex (float currentBackingLufs) const noexcept
    {
        for (int i = static_cast<int> (zones.size()) - 1; i >= 0; --i)
        {
            if (currentBackingLufs >= zones[static_cast<size_t> (i)].lufsLower)
                return i;
        }

        return 0;
    }

    // ────────────────────────────────────────────
    // JSON Serialization (cross-project export/import)
    // ────────────────────────────────────────────

    [[nodiscard]] juce::var toVar() const
    {
        auto* obj = new juce::DynamicObject();
        obj->setProperty ("name", name);
        obj->setProperty ("created", created.toMilliseconds());
        obj->setProperty ("sampleRate", sampleRate);

        juce::Array<juce::var> zonesArray;

        for (const auto& zone : zones)
        {
            auto* zoneObj = new juce::DynamicObject();
            zoneObj->setProperty ("lufsLower", static_cast<double> (zone.lufsLower));
            zoneObj->setProperty ("lufsUpper", static_cast<double> (zone.lufsUpper));
            zoneObj->setProperty ("balanceDb", static_cast<double> (zone.balanceDb));
            zoneObj->setProperty ("dynamicsPercent", static_cast<double> (zone.dynamicsPercent));
            zoneObj->setProperty ("speedMs", static_cast<double> (zone.speedMs));
            zoneObj->setProperty ("rangeDb", static_cast<double> (zone.rangeDb));
            zoneObj->setProperty ("anchorDb", static_cast<double> (zone.anchorDb));
            zoneObj->setProperty ("noiseGateDb", static_cast<double> (zone.noiseGateDb));
            zoneObj->setProperty ("duckFloorDb", static_cast<double> (zone.duckFloorDb));
            zoneObj->setProperty ("boostCeilingDb", static_cast<double> (zone.boostCeilingDb));
            zoneObj->setProperty ("presenceReleaseMs", static_cast<double> (zone.presenceReleaseMs));

            juce::Array<juce::var> bandsArray;

            for (const auto& band : zone.duckBands)
            {
                auto* bandObj = new juce::DynamicObject();
                bandObj->setProperty ("centerHz", static_cast<double> (band.centerHz));
                bandObj->setProperty ("bandwidthQ", static_cast<double> (band.bandwidthQ));
                bandObj->setProperty ("depthDb", static_cast<double> (band.depthDb));
                bandObj->setProperty ("enabled", band.enabled);
                bandsArray.add (juce::var (bandObj));
            }

            zoneObj->setProperty ("duckBands", bandsArray);
            zonesArray.add (juce::var (zoneObj));
        }

        obj->setProperty ("zones", zonesArray);
        return juce::var (obj);
    }

    static TrackProfile fromVar (const juce::var& data)
    {
        TrackProfile profile;
        profile.name = data.getProperty ("name", "").toString();
        profile.created = juce::Time (static_cast<juce::int64> (data.getProperty ("created", 0)));
        profile.sampleRate = static_cast<double> (data.getProperty ("sampleRate", 44100.0));

        if (auto* zonesArray = data.getProperty ("zones", {}).getArray())
        {
            for (const auto& zoneVar : *zonesArray)
            {
                EnergyZone zone;
                zone.lufsLower = static_cast<float> (zoneVar.getProperty ("lufsLower", -100.0));
                zone.lufsUpper = static_cast<float> (zoneVar.getProperty ("lufsUpper", 0.0));
                zone.balanceDb = static_cast<float> (zoneVar.getProperty ("balanceDb", 3.0));
                zone.dynamicsPercent = static_cast<float> (zoneVar.getProperty ("dynamicsPercent", 0.0));
                zone.speedMs = static_cast<float> (zoneVar.getProperty ("speedMs", 120.0));
                zone.rangeDb = static_cast<float> (zoneVar.getProperty ("rangeDb", 8.0));
                zone.anchorDb = static_cast<float> (zoneVar.getProperty ("anchorDb", -24.0));
                zone.noiseGateDb = static_cast<float> (zoneVar.getProperty ("noiseGateDb", -45.0));
                zone.duckFloorDb = static_cast<float> (zoneVar.getProperty ("duckFloorDb", 10.0));
                zone.boostCeilingDb = static_cast<float> (zoneVar.getProperty ("boostCeilingDb", 6.0));
                zone.presenceReleaseMs = static_cast<float> (zoneVar.getProperty ("presenceReleaseMs", 80.0));

                if (auto* bandsArray = zoneVar.getProperty ("duckBands", {}).getArray())
                {
                    for (const auto& bandVar : *bandsArray)
                    {
                        DuckBand band;
                        band.centerHz = static_cast<float> (bandVar.getProperty ("centerHz", 1000.0));
                        band.bandwidthQ = static_cast<float> (bandVar.getProperty ("bandwidthQ", 1.5));
                        band.depthDb = static_cast<float> (bandVar.getProperty ("depthDb", 6.0));
                        band.enabled = static_cast<bool> (bandVar.getProperty ("enabled", true));
                        zone.duckBands.push_back (band);
                    }
                }

                profile.zones.push_back (zone);
            }
        }

        return profile;
    }

    // ────────────────────────────────────────────
    // Binary Serialization (DAW state persistence)
    // ────────────────────────────────────────────

    void writeTo (juce::MemoryOutputStream& stream) const
    {
        stream.writeString (name);
        stream.writeInt64 (created.toMilliseconds());
        stream.writeDouble (sampleRate);
        stream.writeInt (static_cast<int> (zones.size()));

        for (const auto& zone : zones)
        {
            stream.writeFloat (zone.lufsLower);
            stream.writeFloat (zone.lufsUpper);
            stream.writeFloat (zone.balanceDb);
            stream.writeFloat (zone.dynamicsPercent);
            stream.writeFloat (zone.speedMs);
            stream.writeFloat (zone.rangeDb);
            stream.writeFloat (zone.anchorDb);
            stream.writeFloat (zone.noiseGateDb);
            stream.writeFloat (zone.duckFloorDb);
            stream.writeFloat (zone.boostCeilingDb);
            stream.writeFloat (zone.presenceReleaseMs);
            stream.writeInt (static_cast<int> (zone.duckBands.size()));

            for (const auto& band : zone.duckBands)
            {
                stream.writeFloat (band.centerHz);
                stream.writeFloat (band.bandwidthQ);
                stream.writeFloat (band.depthDb);
                stream.writeBool (band.enabled);
            }
        }
    }

    static TrackProfile readFrom (juce::MemoryInputStream& stream)
    {
        TrackProfile profile;
        profile.name = stream.readString();
        profile.created = juce::Time (stream.readInt64());
        profile.sampleRate = stream.readDouble();
        const auto numZones = stream.readInt();

        for (int i = 0; i < numZones && ! stream.isExhausted(); ++i)
        {
            EnergyZone zone;
            zone.lufsLower = stream.readFloat();
            zone.lufsUpper = stream.readFloat();
            zone.balanceDb = stream.readFloat();
            zone.dynamicsPercent = stream.readFloat();
            zone.speedMs = stream.readFloat();
            zone.rangeDb = stream.readFloat();
            zone.anchorDb = stream.readFloat();
            zone.noiseGateDb = stream.readFloat();
            zone.duckFloorDb = stream.readFloat();
            zone.boostCeilingDb = stream.readFloat();
            zone.presenceReleaseMs = stream.readFloat();

            const auto numBands = stream.readInt();

            for (int b = 0; b < numBands && ! stream.isExhausted(); ++b)
            {
                DuckBand band;
                band.centerHz = stream.readFloat();
                band.bandwidthQ = stream.readFloat();
                band.depthDb = stream.readFloat();
                band.enabled = stream.readBool();
                zone.duckBands.push_back (band);
            }

            profile.zones.push_back (zone);
        }

        return profile;
    }

    // ────────────────────────────────────────────
    // JSON File I/O helpers
    // ────────────────────────────────────────────

    bool saveToFile (const juce::File& file) const
    {
        const auto json = juce::JSON::toString (toVar());
        return file.replaceWithText (json);
    }

    static TrackProfile loadFromFile (const juce::File& file)
    {
        const auto json = file.loadFileAsString();
        const auto parsed = juce::JSON::parse (json);
        return fromVar (parsed);
    }
};

} // namespace liveflow
