
pages_build_output_dir = "dist"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "liveflow-db"
database_id = "efee886e-5870-481f-9ea8-304c49e73bac"

[vars]
JWT_SECRET = "REPLACE_WITH_REAL_SECRET_IN_DASHBOARD"
